### ISSUE TITLE
autoForms -> pdf

### ISSUE THREAD

**Issue by flean** [ongoworks/meteor-pdf#3]
Is there a plan to support autoForms to Pdf? Thanks

**Comment by aldeed** [comment]
I don't think there's anything we'd need to do to support it. The main problem would be updating the jsPDF rendering to handle form fields.

**Comment by jaketollette** [comment]
Great package. I don't suppose there's a way to ensure that the styles used on a template is used when the PDF is generated is there?

**Comment by aldeed** [comment]
@jaketollette, that would need to be done in the jsPDF library. I would hope the eventual plan is to use the print stylesheet when generating the PDF.
