### ISSUE TITLE
undefined is not a function error when trying to output a template as pdf

### ISSUE THREAD

**Issue by eventrio** [ongoworks/meteor-pdf#6]
I am trying to use your package to generate a pdf out of a template but I am getting the followong when I try to use it:
     Uncaught TypeError: undefined is not a functionpdf.coffee:13 makePDFpdf.coffee:32
Blaze.outputAsPDForderDetails.js?    3ab5a1e28ba54ae1a4d8f136095448b9af47b065:207   Template.orderDetails.events.click #pdfBtntemplate.js:278 (anonymous function)view.js:760 (anonymous   function)view.js:414 Blaze._withCurrentViewview.js:759 (anonymous function)events.js:47 (anonymous function)jquery.js:4665 jQuery.event.dispatchjquery.js:4333 jQuery.event.add.elemData.handle     

Here is how I am trying to use it. I have a button on a Template, then:

```
"click #pdfBtn":function(evt, tmpl){
    evt.preventDefault();
    console.log(this);
    var data = this;
    Blaze.outputAsPDF(Template.printableInvoice, 'dataurlnewwindow',
        {
            filename: "invoice.pdf", // optional, default is "document.pdf"
            data: data, // optional, render the template with this data context
            format: "letter", // optional, see Page Formats, default is "a4"
            unit:"in",
            orientation:"portrait"
        });
}
```

My printable template is defined like this:

```
<template name="printableInvoice">
<span>Order #:<br/> {{_id}}</span>
<span>Ordered From:<br /> {{vendorName}}</span>
<span>Total:<br /> {{formatCurrency total}}</span>
<span>Show:<br /> {{showName}}</span>
<span>Payment Date:<br /> {{formatDate scheduledDate}}</span>
<span>Payment Method:<br /> {{paymentMethod}}</span>

{{#each products}}
    <div class="media">
        <div class="media-left">
            <a href="{{productDetailsUrl}}">
                <img class="media-object" src="{{productImageUrl}}" style="max-height:6em;" alt="{{productName}}">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{productName}}</h4>
            <div class="col-md-8">
                <span>Terms: {{productTerms}}</span><br>
                <span>Booth #: {{boothNumber}}</span><br>
                <span>Quantity Ordered: {{quantityOrdered}}</span><br>
                <span>Product Total: {{formatCurrency price}}</span><br>

            </div>

        </div>
    </div>
    <hr>
{{/each}}
</template>
```

Am I doing something wrong here? I thought this was a pretty trivial use case.

**Comment by eventrio** [comment]
For giggles I tried using:

    Blaze.saveAsPDF(Template.printableInvoice, {
	filename: "invoice.pdf",
	data: data,
	x: 0, 
        y: 0, 
	orientation: "landscape",
	unit: "in",
	format: "letter" 
    });


And got the same error as before.

**Comment by aldeed** [comment]
It seems like there's a function missing from the jsPDF API in your build. Are you adding a different version of jsPDF separately? It's included with this package, so you shouldn't add it to your app yourself.

Otherwise I don't know what would cause the error. You will have to create an app that reproduces the issue for us to investigate.

**Comment by eventrio** [comment]
I followed the instructions as they are in the readme for this repo and on the Atmosphere page for this package so I didn't add anything other than this package. I will try removing it and adding it again to see if maybe something just got messed up in the installation of the package. If that doesn't fix it then I will see about creating an app that reproduces the problem.

**Comment by eventrio** [comment]
So a clean install didn't fix anything, and creating an app that will replicate the problem could take forever and I don't have that kind of time. 
I can clearly see the fromHTML function when I browse the source file **jspdf.debug.js**, but when I inspect the code in pdf.coffee there is no fromHTML function as an attribute of "doc" after the following code executes:

    doc = new jsPDF options.orientation, options.unit, options.format
    options:{ 
        data: Object,
        filename: "invoice.pdf",
        format: "letter",
        orientation: "landscape",
        unit: "in",
        x: 4,
        y: 4,
    }

This code was taken from line 14 of pdf.coffee...

The variable doc looks like this in the console:

    CapJoinStyles: Object
    addImage: function (imageData, format, x, y, w, h) { // 141
    addPage: function () { // 1133
    circle: function (x, y, r, style) { // 1495
    ellipse: function (x, y, rx, ry, style) { // 1435
    events: Array[0]
    getFontList: function () { // 1578
    internal: Object
    line: function (x1, y1, x2, y2) { // 1234
    lines: function (lines, x, y, scale, style, closed) { // 1261
    output: function (type, options) { // 985
    rect: function (x, y, w, h, style) { // 1342
    roundedRect: function (x, y, w, h, rx, ry, style) { // 1401
    save: function (filename) { // 1856
    setDrawColor: function (ch1, ch2, ch3, ch4) { // 1650
    setFillColor: function (ch1, ch2, ch3, ch4) { // 1716
    setFont: function (fontName, fontStyle) { // 1544
    setFontSize: function (size) { // 1528
    setFontStyle: function (style) { // 1561
    setFontType: function (style) { // 1561
    setLineCap: function (style) { // 1812
    setLineJoin: function (style) { // 1833
    setLineWidth: function (width) { // 1608
    setProperties: function (properties) { // 1508
    setTextColor: function (r, g, b) { // 1759
    text: function (text, x, y, flags) { // 1149
    triangle: function (x1, y1, x2, y2, x3, y3, style) { // 1370
    onDone: function () {
    options: Object
    selector: undefined
    this: Window


The resulting html from the printable template is:

    "<table>
		<thead>
			<th>Order # </th>
			<th>Vendor</th>
			<th>Total</th>
			<th>Show</th>
			<th>Payment Date</th>
			<th>Payment Method</th>
		</thead>
		<tbody>
			<tr>
				<td>9ySTkq74uaAn3SfJ2</td>
				<td>George R. Brown Convention Center</td>
				<td>215.60000000000002</td>
				<td>Grace Hopper Celebration Conference</td>
				<td>Thu Apr 23 2015 00:00:00 GMT-0500 (CDT)</td>
				<td>Card xxxxxxxxxxxx1111</td>
			</tr>
		</tbody>
	</table>
	<h1>Products</h1>
	<table>
		<thead>
			<th></th>
			<th>Name</th>
			<th>Terms</th>
			<th>Booth Number</th>
			<th>Quantity</th>
			<th>Product Total</th>
			
			
		</thead>
		<tbody>
			
			<tr>
				<td><img class="media-object" src="https://res.cloudinary.com/dzvv7dsjc/image/upload/v1422651757/GRB_CC_Bagels_hqpjb4.jpg" style="max-height:3em;" alt="Catering - Breakfast Items - Baked Goods - Bagels with Cream Cheese"></td>
				<td>Catering - Breakfast Items - Baked Goods - Bagels with Cream Cheese</td>
				<td>Food will be delivered by a certified food handler. Tables and silverware purchased separately.</td>
				<td>123456</td>
				<td></td>
				<td>631.8000000000001</td>
				
			</tr>
			
		</tbody>
	</table>"



I am thinking there is a conflict with another package, but I have no idea which one. I am using quite a few packages and don't really have time to go through and remove them one by one and fix the resulting errors in order to track down which it is.
